# Generated by Django 4.2 on 2024-10-14 23:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def create_users_and_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')  # Get the User model
    Profile = apps.get_model('profiles', 'Profile')  # Get the Profile model

    # Define user data
    users_data = [
        {"username": "user1", "password": "password123", "job_title": "Engineer", "reason_for_searching": "Looking for growth opportunities."},
        {"username": "user2", "password": "password123", "job_title": "Data Analyst", "reason_for_searching": "Seeking a career change."},
        {"username": "user3", "password": "password123", "job_title": "Project Manager", "reason_for_searching": "Exploring management roles."},
        {"username": "user4", "password": "password123", "job_title": "Software Developer", "reason_for_searching": "Wants to work on new projects."},
        {"username": "user5", "password": "password123", "job_title": "Designer", "reason_for_searching": "Interested in creative opportunities."},
        {"username": "user6", "password": "password123", "job_title": "Marketing Specialist", "reason_for_searching": "Exploring new market trends."}
    ]

    # Create users and profiles
    for user_data in users_data:
        if not User.objects.filter(username=user_data["username"]).exists():
            user = User.objects.create_user(username=user_data["username"], password=user_data["password"])
            Profile.objects.create(
                user=user,
                job_title=user_data["job_title"],
                reason_for_searching=user_data["reason_for_searching"],
                start_date=datetime.date.today(),
                follow_up_no_of_days=7  # Default
            )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('reason_for_searching', models.TextField()),
                ('follow_up_no_of_days', models.IntegerField(default=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_users_and_profiles),
    ]
