# Generated by Django 4.2 on 2024-10-14 23:04

import colorfield.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=30)),
                ('job_link_description', models.URLField()),
                ('application_posted', models.DateField()),
                ('date_applied', models.DateField(default=datetime.date.today)),
                ('cv', models.FileField(blank=True, null=True, upload_to='')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='')),
                ('date_last_followup', models.DateField()),
                ('recruiter_name', models.CharField(max_length=80)),
                ('recruiter_email', models.EmailField(max_length=250)),
                ('manager_name', models.CharField(max_length=80)),
                ('manager_email', models.EmailField(max_length=250)),
                ('company_name', models.CharField(max_length=60)),
                ('company_website', models.URLField()),
                ('status', models.CharField(choices=[('not_applied', 'Not Applied Yet'), ('applied', 'Applied'), ('viewed', 'Application Viewed'), ('under_review', 'Application Under Review'), ('assessment_scheduled', 'Assessment/Test Scheduled'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('follow_up', 'Follow-Up Required'), ('offer_extended', 'Offer Extended'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('hired', 'Hired')], default='not_applied', max_length=20)),
                ('notes', models.TextField()),
                ('next_stage_date_time', models.DateTimeField()),
                ('next_stage_prep', models.TextField()),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, to='job_application.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
