# Generated by Django 4.2 on 2024-10-17 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title'),
        ),
    ]
