# Generated by Django 4.2 on 2024-10-17 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20241017_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='contact_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv.contactdetails'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='education_items',
            field=models.ManyToManyField(blank=True, null=True, to='cv.educationitem'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='hackathon_items',
            field=models.ManyToManyField(blank=True, null=True, to='cv.hackathonitem'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='personal_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv.personalprofile'),
        ),
    ]
